import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { createdAt, id } from "./_shared";
import { groups } from "./groups";
import { topics } from "./topics";

export const conversationSessions = pgTable("conversation_sessions", {
  id: id(),
  groupId: uuid("group_id")
    .notNull()
    .references(() => groups.id),
  topicId: uuid("topic_id").references(() => topics.id, { onDelete: "set null" }),
  mode: text("mode", { enum: ["PREVIEW", "MANUAL", "AUTOMATIC"] }).notNull(),
  status: text("status", {
    enum: ["DRAFT", "PENDING_APPROVAL", "SENDING", "COMPLETED", "CANCELLED", "FAILED"],
  })
    .notNull()
    .default("DRAFT"),
  environment: text("environment", { enum: ["PRIVATE_SIMULATION", "REAL_COMMUNITY"] }).notNull(),
  startedAt: timestamp("started_at", { withTimezone: true }),
  endedAt: timestamp("ended_at", { withTimezone: true }),
  /** GENERATED by the AI, or IMPORTED from an uploaded Excel/PDF/CSV file. */
  source: text("source", { enum: ["GENERATED", "IMPORTED"] })
    .notNull()
    .default("GENERATED"),
  /** Optional label (imports carry their own title/topic text; generated ones use the topic). */
  title: text("title"),
  /** Set when the scheduler created/claimed this session; drives quota and quiet-hour checks. */
  scheduleId: uuid("schedule_id"),
  createdAt: createdAt(),
}).enableRLS();
